pipelines:
  default:
    - step:
        name: CD DIR
        script:
            # Grab the Android Support Repo which isn't included in the container
            - unset ANDROID_NDK_HOME
            - cd ATPKit/ATPBuild
            - ls
            
    - step:
        name: UPLOAD iOS SDK TO AWS S3
        image: atlassian/pipelines-awscli
        trigger: manual
        script:  
            ##########  UPLOAD SDK TO AWS S3 ##########
            - ls
            - cd ATPKit/ATPBuild
            - ls
            - aws s3 cp ATP_iOS_SDK s3://releases.atlasp.io/sdk/SDK-IOS/ --recursive
            
    - step:
        name: UPLOAD Release SDK TO AWS S3
        image: atlassian/pipelines-awscli
        trigger: manual
        script:  
            ##########  UPLOAD SDK TO AWS S3 ##########
            - ls
            - cd ATPKit/ATPBuild
            - ls
            - aws s3 cp ATP_iOS_Release s3://releases.atlasp.io/sdk/SDK-IOS/ --recursive