# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!
target 'ATPKit' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    
    pod 'Alamofire'
    pod 'DLRadioButton'
    pod 'SnapKit','~>3.2.0'
    pod 'SDWebImage'
    #  pod 'SDWebImage/GIF'
    
    target 'ATPKitTests' do
        inherit! :search_paths
        #    pod 'Alamofire'
        #    pod 'DLRadioButton'
        #    pod 'SnapKit','~>3.2.0'
        #    pod 'SDWebImage'
        # Pods for testing
    end
end



post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
            config.build_settings['ENABLE_BITCODE'] = 'YES'
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
