# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'Renderer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
#  pod 'Validator','~> 2.1.1'
  pod 'DLRadioButton'
  # Pods for Renderer

  target 'RendererTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
